export const turfs = [
  {
    id: 1,
    name: "Green Arena",
    location: "Koramangala, Bangalore",
    city: "Bangalore",
    price: 1200,
    rating: 4.8,
    reviews: 234,
    sport: "Football",
    images: [
      "https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800&q=80",
      "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800&q=80",
      "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    ],
    description: "Premium 7-a-side football turf with FIFA-approved synthetic grass, floodlights, and changing rooms. Perfect for evening matches and weekend tournaments.",
    amenities: ["Floodlights", "Changing Room", "Parking", "Water", "First Aid"],
    featured: true,
  },
  {
    id: 2,
    name: "StrikeZone Cricket",
    location: "HSR Layout, Bangalore",
    city: "Bangalore",
    price: 1500,
    rating: 4.6,
    reviews: 189,
    sport: "Cricket",
    images: [
      "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80",
      "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80",
    ],
    description: "Indoor box cricket arena with professional-grade pitch and nets. Ideal for practice sessions and corporate events.",
    amenities: ["Indoor", "AC", "Cafeteria", "Parking", "Scorecard"],
    featured: true,
  },
  {
    id: 3,
    name: "Urban Kick",
    location: "Indiranagar, Bangalore",
    city: "Bangalore",
    price: 800,
    rating: 4.3,
    reviews: 312,
    sport: "Football",
    images: [
      "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=800&q=80",
      "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    ],
    description: "Compact 5-a-side turf in the heart of Indiranagar. Great for quick games after work. Budget-friendly with great vibes.",
    amenities: ["Floodlights", "Water", "Parking"],
    featured: false,
  },
  {
    id: 4,
    name: "Smash Court",
    location: "Andheri, Mumbai",
    city: "Mumbai",
    price: 2000,
    rating: 4.9,
    reviews: 156,
    sport: "Badminton",
    images: [
      "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&q=80",
    ],
    description: "Professional badminton courts with wooden flooring, proper lighting, and air conditioning. Shuttles available for purchase.",
    amenities: ["Indoor", "AC", "Changing Room", "Equipment Rental", "Cafeteria"],
    featured: true,
  },
  {
    id: 5,
    name: "PowerPlay Arena",
    location: "Bandra, Mumbai",
    city: "Mumbai",
    price: 1800,
    rating: 4.7,
    reviews: 278,
    sport: "Box Cricket",
    images: [
      "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80",
    ],
    description: "State-of-the-art box cricket facility with artificial turf, automatic scoring, and live streaming capabilities.",
    amenities: ["Indoor", "AC", "Live Streaming", "Scoring System", "Cafeteria"],
    featured: true,
  },
  {
    id: 6,
    name: "The Goal Post",
    location: "Whitefield, Bangalore",
    city: "Bangalore",
    price: 1000,
    rating: 4.4,
    reviews: 198,
    sport: "Football",
    images: [
      "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    ],
    description: "Well-maintained 5-a-side and 7-a-side turfs with premium synthetic grass. Great for league matches and friendly games.",
    amenities: ["Floodlights", "Changing Room", "Parking", "Water"],
    featured: false,
  },
  {
    id: 7,
    name: "Net Practice Hub",
    location: "Juhu, Mumbai",
    city: "Mumbai",
    price: 600,
    rating: 4.1,
    reviews: 87,
    sport: "Cricket",
    images: [
      "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80",
    ],
    description: "Affordable cricket nets for focused practice. Bowling machines available for rent. Perfect for individual skill building.",
    amenities: ["Bowling Machine", "Nets", "Water"],
    featured: false,
  },
  {
    id: 8,
    name: "Ace Tennis Club",
    location: "Powai, Mumbai",
    city: "Mumbai",
    price: 2500,
    rating: 4.8,
    reviews: 143,
    sport: "Tennis",
    images: [
      "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=800&q=80",
    ],
    description: "Clay and hard courts with international-standard dimensions. Coaching sessions available. Club membership benefits included.",
    amenities: ["Coaching", "Club House", "Shower", "Parking", "Equipment"],
    featured: true,
  },
];

export const timeSlots = [
  { time: "12:00 AM", status: "available" },
  { time: "01:00 AM", status: "available" },
  { time: "02:00 AM", status: "available" },
  { time: "03:00 AM", status: "available" },
  { time: "04:00 AM", status: "available" },
  { time: "05:00 AM", status: "available" },
  { time: "06:00 AM", status: "available" },
  { time: "07:00 AM", status: "available" },
  { time: "08:00 AM", status: "booked" },
  { time: "09:00 AM", status: "booked" },
  { time: "10:00 AM", status: "available" },
  { time: "11:00 AM", status: "available" },
  { time: "12:00 PM", status: "unavailable" },
  { time: "01:00 PM", status: "unavailable" },
  { time: "02:00 PM", status: "available" },
  { time: "03:00 PM", status: "available" },
  { time: "04:00 PM", status: "booked" },
  { time: "05:00 PM", status: "available" },
  { time: "06:00 PM", status: "available" },
  { time: "07:00 PM", status: "booked" },
  { time: "08:00 PM", status: "available" },
  { time: "09:00 PM", status: "available" },
  { time: "10:00 PM", status: "available" },
  { time: "11:00 PM", status: "available" },
];

export const userBookings = [
  {
    id: "BK-2847",
    turfId: 1,
    turfName: "Green Arena",
    location: "Koramangala, Bangalore",
    date: "2026-03-22",
    slot: "06:00 PM",
    price: 1200,
    status: "confirmed",
    sport: "Football",
  },
  {
    id: "BK-2901",
    turfId: 5,
    turfName: "PowerPlay Arena",
    location: "Bandra, Mumbai",
    date: "2026-03-25",
    slot: "08:00 PM",
    price: 1800,
    status: "confirmed",
    sport: "Box Cricket",
  },
  {
    id: "BK-2610",
    turfId: 3,
    turfName: "Urban Kick",
    location: "Indiranagar, Bangalore",
    date: "2026-03-10",
    slot: "07:00 PM",
    price: 800,
    status: "completed",
    sport: "Football",
  },
  {
    id: "BK-2455",
    turfId: 2,
    turfName: "StrikeZone Cricket",
    location: "HSR Layout, Bangalore",
    date: "2026-02-28",
    slot: "05:00 PM",
    price: 1500,
    status: "cancelled",
    sport: "Cricket",
  },
];

export const ownerStats = {
  totalEarnings: 247800,
  monthlyEarnings: 68500,
  totalBookings: 342,
  activeListings: 3,
  peakDay: "Saturday",
  peakSlot: "6:00 PM - 8:00 PM",
  earningsData: [
    { month: "Oct", amount: 42000 },
    { month: "Nov", amount: 51200 },
    { month: "Dec", amount: 38600 },
    { month: "Jan", amount: 47500 },
    { month: "Feb", amount: 59200 },
    { month: "Mar", amount: 68500 },
  ],
  bookingsPerDay: [
    { day: "Mon", count: 8 },
    { day: "Tue", count: 6 },
    { day: "Wed", count: 9 },
    { day: "Thu", count: 7 },
    { day: "Fri", count: 12 },
    { day: "Sat", count: 18 },
    { day: "Sun", count: 15 },
  ],
};

export const sports = [
  { name: "Football", icon: "⚽", count: 48 },
  { name: "Cricket", icon: "🏏", count: 35 },
  { name: "Box Cricket", icon: "🏏", count: 22 },
  { name: "Badminton", icon: "🏸", count: 19 },
  { name: "Tennis", icon: "🎾", count: 12 },
  { name: "Basketball", icon: "🏀", count: 8 },
];

export const cities = ["Bangalore", "Mumbai", "Delhi", "Hyderabad", "Chennai", "Pune"];
